import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ClientAppLayout from "./ClientAppLayout"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "AkwaabaHRPay",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientAppLayout>{children}</ClientAppLayout>
      </body>
    </html>
  )
}
