-- Clear existing subsidiary data and replace with new comprehensive data
DELETE FROM subsidiaries;

-- Insert new comprehensive subsidiary data
INSERT INTO subsidiaries (
  id,
  company_id,
  name,
  tax_id,
  ssnit_number,
  address,
  phone_number,
  email_address,
  logo_url,
  status,
  industry,
  divisions,
  departments,
  locations,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Akwaaba Digital Solutions',
  'TIN-ADS-2023-001',
  'SSNIT-ADS-789012',
  '15 Liberation Road, Ridge, Accra, Ghana',
  '+233 30 276 5432',
  'info@akwaabadigital.com',
  '/placeholder.svg?height=40&width=40',
  'active',
  'Digital Marketing & Web Development',
  '["Technology", "Marketing", "Operations"]'::jsonb,
  '["Web Development", "Digital Marketing", "Customer Support", "Finance"]'::jsonb,
  '["Accra Head Office", "Kumasi Branch"]'::jsonb,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Akwaaba Manufacturing Ltd',
  'TIN-AML-2023-002',
  'SSNIT-AML-789013',
  '45 Industrial Area, Tema, Ghana',
  '+233 30 303 7890',
  'operations@akwaabamanufacturing.com',
  '/placeholder.svg?height=40&width=40',
  'active',
  'Manufacturing & Production',
  '["Production", "Quality Control", "Logistics"]'::jsonb,
  '["Production", "Quality Assurance", "Warehouse", "Maintenance", "HR"]'::jsonb,
  '["Tema Factory", "Takoradi Warehouse"]'::jsonb,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Akwaaba Financial Services',
  'TIN-AFS-2023-003',
  'SSNIT-AFS-789014',
  '12 Oxford Street, Osu, Accra, Ghana',
  '+233 30 276 1234',
  'contact@akwaabafinancial.com',
  '/placeholder.svg?height=40&width=40',
  'active',
  'Financial Services',
  '["Retail Banking", "Corporate Banking", "Investment"]'::jsonb,
  '["Loans", "Savings", "Investment Advisory", "Risk Management"]'::jsonb,
  '["Accra Main", "Kumasi Branch", "Tamale Branch"]'::jsonb,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Akwaaba Logistics Hub',
  'TIN-ALH-2023-004',
  'SSNIT-ALH-789015',
  '78 Spintex Road, Accra, Ghana',
  '+233 30 276 9876',
  'logistics@akwaabahub.com',
  '/placeholder.svg?height=40&width=40',
  'active',
  'Logistics & Transportation',
  '["Freight", "Warehousing", "Distribution"]'::jsonb,
  '["Transportation", "Warehousing", "Customs", "Fleet Management"]'::jsonb,
  '["Accra Hub", "Tema Port", "Kumasi Center"]'::jsonb,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM companies LIMIT 1),
  'Akwaaba Retail Chain',
  'TIN-ARC-2023-005',
  'SSNIT-ARC-789016',
  '23 Kwame Nkrumah Avenue, Accra, Ghana',
  '+233 30 276 5555',
  'retail@akwaabachain.com',
  '/placeholder.svg?height=40&width=40',
  'inactive',
  'Retail & Consumer Goods',
  '["Retail Operations", "Merchandising", "Customer Service"]'::jsonb,
  '["Store Operations", "Merchandising", "Customer Service", "Inventory"]'::jsonb,
  '["Accra Mall", "West Hills Mall", "Kumasi City Mall"]'::jsonb,
  NOW(),
  NOW()
);
